<?php

$page = $_GET['page'];



if (($module != null ) AND ($view != null)) {
	
	/*Check the $module for validitity - make sure no ones hacking the url */
	if (!ereg("^[a-z_/]+$",$page)) { 
        	die("Invalid page requested");
	}



	/*Check to make sure that the requested files exist*/
	if (file_exists("./src/$page.php")) {
	        include("./src/include/design/header.inc.php");
	        include("./src/$module/$view.php");
        	include("./src/include/design/footer.inc.php");
	}
	else {
		include("./src/include/design/header.inc.php");
		echo "The file that you requested doesn't exist";
		include("./src/include/design/footer.inc.php");
	}
}

/*If all else fails show the start.php page */
else {
        include("./src/include/design/header.inc.php");
        include("start.php");
        include("./src/include/design/footer.inc.php");
}

?>








<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">

<html><head><title>Home</title><link rel="stylesheet" type="text/css" href="../../styles/main.css"><script language=JavaScript src="../../javascript/main.js"></script><script language=JavaScript src="../../javascript/searchdata.js"></script></head><body id=ContentPage onLoad="NDOnLoad()"><script language=JavaScript><!--
if (browserType) {document.write("<div id=" + browserType + ">");if (browserVer) {document.write("<div id=" + browserVer + ">"); }}// --></script>

<!--  Generated by Natural Docs, version Development Release 02-10-2007 (1.35 base) -->
<!--  http://www.naturaldocs.org  -->

<!-- saved from url=(0026)http://www.naturaldocs.org -->



<!-- Content start -->
<?php include
<div id=Content>

<h1 class=CTitle align=right><a name="About"></a>Simple Invoices</h1>

<h4 class=CHeading align=center><a href="">Online demo</a> :: <a href="">Download</a> :: <a href="">Get Involved</a> :: <a href="">Forum</a> :: <a href="">Blog</a> :: <a href="">Wiki</a></h4>


<div class="CFile CTopic" id=MainTopic><h1 class=CTitle><a name="Home"></a>Home</h1><div class=CBody><p class=CParagraph>Simple Invoices</p><p class=CParagraph>Free/Open source software, no betas, no marketing, no buzz words, no whizz bang features your never ganna use, just a simple invoicing system designed to get the job done.</p><p class=CParagraph>Read more &gt;           Quick Tour &gt;           Online demo &gt;</p><p class=CParagraph>Show RSS info here</p></div></div>

</div><!--Content end-->


<div id=Footer><a href="http://www.naturaldocs.org">Generated by Natural Docs</a></div><!--Footer-->


<!-- Menu start -->
<div id=Menu>

<div class="MGroup MEntry"><a href="javascript:ToggleMenu('MGroupContent3')">Menu</a><div class=MGroupContent id=MGroupContent3>
	<div class="MFile MEntry"><a href="About-php.html">About</a></div>
	<div class="MFile MEntry"><a href="Contact-php.html">Contact</a></div>
	<div class="MFile MEntry"><a href="Download-php.html">Download</a></div>
	<div class="MFile MEntry"><a href="Features-php.html">Features</a></div>
	<div class="MFile MEntry"><a href="GetInvolved-php.html">Get Involved</a></div>
	<div class="MFile MEntry"><a href="GetInvolved-php.html">Home</a></div>

	<!-- Selected Code -->
	<!--
	<div class="MFile MEntry" id=MSelected>Home</div>
	-->

	<div class="MFile MEntry"><a href="Online_Demo-php.html">Online Demo</a></div>
	<div class="MFile MEntry"><a href="Philosophy-php.html">Philosophy</a></div></div></div>

<div class="MGroup MEntry"><a href="javascript:ToggleMenu('MGroupContent1')">Community</a><div class=MGroupContent id=MGroupContent1>
	<div class="MFile MEntry"><a href="../Community/Blog-php.html">Blog</a></div>
	<div class="MFile MEntry"><a href="../Community/Fourm-php.html">Forum</a></div>
	<div class="MFile MEntry"><a href="../Community/GetInvolved-php.html">Get Involved</a></div>
	<div class="MFile MEntry"><a href="../Community/Wiki-php.html">Wiki</a></div></div></div>
<div class="MGroup MEntry"><a href="javascript:ToggleMenu('MGroupContent2')">Dev</a><div class=MGroupContent id=MGroupContent2>
	<div class="MFile MEntry"><a href="../Dev/Change_Log-php.html">Change Log</a></div><div class="MFile MEntry"><a href="../Dev/Code-php.html">Code</a></div>
	<div class="MFile MEntry"><a href="../Dev/Credits-php.html">Credits</a></div>
	<div class="MFile MEntry"><a href="../Dev/Dev_FAQs-php.html">Dev FAQs</a></div>
	<div class="MFile MEntry"><a href="../Dev/Dev_Site-php.html">Dev Site</a></div>
	<div class="MFile MEntry"><a href="../Dev/Lang_Check-php.html">Lang Check</a></div></div></div>




<!--START_ND_TOOLTIPS-->
<!--END_ND_TOOLTIPS-->




<script language=JavaScript><!--
if (browserType) {if (browserVer) {document.write("</div>"); }document.write("</div>");}// --></script></body></html>
