

<div class="CFile CTopic" id=MainTopic><h1 class=CTitle><a name="About"></a>About</h1><div class=CBody>

<p class=CParagraph>

Simple Invoices ...&nbsp; a simple invoicing system designed to get the job done, Free/Open source software, community developed, no marketing, no buzz words, and no whizzbang features your never ganna use.</p><p class=CParagraph>Simple Invoices started out in mid 2005 to fulfil my need for a simple system to create invoices.&nbsp; I had no desire to waste my time with spreadsheets and wasn&rsquo;t interestd in any of the invoicing solutions, they all seemed to big and complex, requiring me to set up a fulll CRM/ERP system with users/passwords/blah blah just to create a simple invoice that should only take seconds to create. and thus SImple Invoices was born.</p>
<p class=CParagraph>My goal was a system where I could just select a biller(me), a customer, type some details of the work being invoicing and a total, hit a button and a nice looking invoice would be created.&nbsp; This simple goal was achieved in the first release.</p><p class=CParagraph>Since this release more features have been added to make Simple Invoices useful for people other than myself :) (refer Features)</p><p class=CParagraph>But the aim has (and always will be) to keep Simple Invoices simple.</p><p class=CParagraph>The development of Simple Invoices has worked hard to make it as flexable and yet basic as possible.&nbsp; If you want to do simple stuff, then it should be simple and the software should get out of your way.&nbsp; If you want to do more complex stuff then it should be possible (just look in the Options menu :) )</p><p class=CParagraph>If all you want to do is whip up a quick invoice every now and againg this should and IS simple.&nbsp; But if you want a more complex setup with customised invoices, payment tracking, PDFing, etc.. this all all there aswell.</p><h4 class=CHeading>Who/What is this aimed for</h4><ul class=CBulletList><li>Personal invoices</li><li>Home office invoicing</li><li>Small organisation invoicing</li><li>Basic POS(point of sale) system for light usage(ie not in a Starbucks..)</li></ul><h4 class=CHeading>Goals</h4><ul class=CBulletList><li>Easy to use invoicing system</li><li>No hassles software</li><li>Keep it simple and clean</li><li>Does one thing and does it well</li><li>Focused on producing a great invoicing system - thats it.</li></ul><h4 class=CHeading>NOT Goals</h4><ul class=CBulletList><li>Full on accouting system</li><li>Stacks of features</li><li>Millions of options</li></ul></div></div>
</div><!--Content end-->
