<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">

<html><head><title>Simple Invoices</title><link rel="stylesheet" type="text/css" href="./styles/main.css"><script language=JavaScript src="./javascript/main.js"></script><script language=JavaScript src="./javascript/searchdata.js"></script>
<script type="text/javascript" src="./src/include/jquery.js"></script>
<script type="text/javascript" src="./src/include/interface.js"></script>
<link rel="stylesheet" type="text/css" href="./src/include/tour.css">
</head><body id=ContentPage onLoad="NDOnLoad()"><script language=JavaScript><!--
if (browserType) {document.write("<div id=" + browserType + ">");if (browserVer) {document.write("<div id=" + browserVer + ">"); }}// --></script>

<!--  Generated by Natural Docs, version Development Release 02-10-2007 (1.35 base) -->
<!--  http://www.naturaldocs.org  -->

<!-- saved from url=(0026)http://www.naturaldocs.org -->



<!-- Content start -->
<div id=Content>

<h1 class=CTitle align=right><a name="Simple Invoices"></a><a href="index.php" class="title">Simple Invoices</a></h1>

<h4 class=CHeading align=center><a href="http://www.simpleinvoices.org/demo">Online demo</a> :: <a href="http://sourceforge.net/project/showfiles.php?group_id=164303">Download</a> :: <a href="index.php?page=GetInvolved">Get Involved</a> :: <a href="http://www.simpleinvoices.org/forum">Forum</a> :: <a href="http://www.simpleinvoices.org/blog">Blog</a> :: <a href="http://www.simpleinvoices.org/wiki">Wiki</a></h4>


<!-- Flags and translation -->
<!--
<a title="Francais" href="http://translate.google.com/translate?u=http%3A%2F%2Fwww.simpleinvoices.org&langpair=en%7Cfr&hl=en&ie=UTF8"><img src="./src/flags/flag_fr.gif" alt="French"></img></a>

<a title=Chinese  href="http://translate.google.com/translate?u=http%3A%2F%2Fwww.simpleinvoices.org&langpair=en%7Czh-CN&hl=en&ie=UTF8/"><img src="./src/flags/flag_zh-CN.gif" alt="Chinese"></img></a>

<a title=Deutsch  href="http://translate.google.com/translate?u=http%3A%2F%2Fwww.simpleinvoices.org&langpair=en%7Cde&hl=en&ie=UTF8"><img src="./src/flags/flag_de.gif" alt="German"></img></a>

<a title="Italiano"  href="http://translate.google.com/translate?u=http%3A%2F%2Fwww.simpleinvoices.org&langpair=en%7Cit&hl=en&ie=UTF8"><img src="./src/flags/flag_it.gif" alt="Italian"></img></a>

<a title="Japanese"  href="http://translate.google.com/translate?u=http%3A%2F%2Fwww.simpleinvoices.org&langpair=en%7Cja&hl=en&ie=UTF8"><img src="./src/flags/flag_ja.gif" alt="Japan"></img></a>

<a title="Korean"  href="http://translate.google.com/translate?u=http%3A%2F%2Fwww.simpleinvoices.org&langpair=en%7Cko&hl=en&ie=UTF8"><img src="./src/flags/flag_ko.gif" alt="Korean"></img></a>

<a title="Portugese"  href="http://translate.google.com/translate?u=http%3A%2F%2Fwww.simpleinvoices.org&langpair=en%7Cpt&hl=en&ie=UTF8"><img src="./src/flags/flag_pt.gif" alt="Portugese"></img></a>

<a title="Espanol"  href="http://translate.google.com/translate?u=http%3A%2F%2Fwww.simpleinvoices.org&langpair=en%7Ces&hl=en&ie=UTF8/"><img src="./src/flags/flag_es.gif" alt="Espanol"></img></a>

<a title="Arabic" href="http://translate.google.com/translate?u=http%3A%2F%2Fwww.simpleinvoices.org&langpair=en%7Car&hl=en&ie=UTF8"><img src="./src/flags/flag_ar.gif" alt="Arabic"></img></a>
-->
